### ISSUE TITLE
Produces multiple times the output when run with Gulp

### ISSUE THREAD

**Issue by jkphl** [zgreen/postcss-critical-css#15]
Since you fixed #12 with #13 — thanks, *probably* works like a charm! — there's a new bug which makes the module quite unusable when used with Gulp: For no obvious reason, the critical CSS now contains its output multiple times.

Please use this simple `gulpfile.js` for reproducing the error:

```js
const gulp = require('gulp');
const postcss = require('gulp-postcss');
const critical = require('.');

gulp.task('css', () => {
   gulp.src('example/example.css').
    pipe(postcss([
        critical({
            outputPath: `example/test`,
            outputDest: `critical.css`,
            preserve: true,
            minify: false,
        }),
    ]))
    .pipe(gulp.dest('example/test'));
});
```
Rendering this modified `example/example.css`:

```css
@media  {
  .foo {
    display: flex;
    width: calc(100% - 200px);
  }

  .bar {
    border: 10px solid gold;
    height: 100%;
  }

  .baz::before {
    critical-selector: this;
    content: 'test';
    position: fixed;
  }
}
```

will result in the following `example/test/critical.css`:

```css
@media {
    .baz::before {
        content: 'test';
        position: fixed
    }
    .baz::before {
        content: 'test';
        position: fixed
    }
    .baz::before {
        content: 'test';
        position: fixed
    }
}
@media {
    .baz::before {
        content: 'test';
        position: fixed
    }
    .baz::before {
        content: 'test';
        position: fixed
    }
    .baz::before {
        content: 'test';
        position: fixed
    }
}
@media {
    .baz::before {
        content: 'test';
        position: fixed
    }
    .baz::before {
        content: 'test';
        position: fixed
    }
    .baz::before {
        content: 'test';
        position: fixed
    }
}
```

I'm running:

* Node v6.6.0
* npm v3.10.3
* Gulp 3.9.1

A fix would very much be appreciated as we're about to roll out the project rather soon. Thanks!
